#+TITLE:     Notes on the INTRODUCTION to the Phenomenology of Spirit (Mind).
#+AUTHOR:    GW Dean
#+EMAIL:     gwdean@gmail.com
#+DATE:      2013-10-08 Tue
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
* Muller-1970
The long Preface of the /Phenomenology of Mind/ is followed by thirteen
pages, now called Introduction, which contains 16 sections.

These pages are something like a long subtitle explaining the meaning 
of the title, which is still meant to be the title of the book in 
section XV.

Heraclitus quotation (from the title page of the /PoM/):
"The soul's meaning is self-augmenting."

At the end of the /Phenomenology/, Hegel says that the 
world-consciousness as developed in the medium of the soul
is a preparation for /Logic/.
** Philosophical Knowledge
Philosophical knowledge is neither a practical tool, by
which the Absolute could be handled, nor a theoretical medium
of reception. Both forms of empirical knowledge postulate a
separation between an object known and empirical subjects 
knowing it. The Absolute is both Being in itself and Subject
for itself. Truth is the ontological consciousness of Being
in us, the One becoming aware of itself in many beings.
** Our Fear of Error and Untruth
Our fear of error and untruth is a testimony to the presence
of the absolute consciousness in our existence.
** The Absolute is the Only Truth
The Absolute is the only truth, and only truth is absolute.
The absolute whole is presupposed (/vorausgesetzt/) by and 
in all empirical informations. To "know all" is not knowledge
of wholeness or integrity. This ground of philosophy is at 
the same time the goal of its self-development.
** Philosophy Is Not One Position Among Others
Philosophy is not one position among others; it cannot withdraw
to an inner certainty, a sentiment, a voluntaristic choice, an
arbitrary faith, or an intuitive hunch. It has to go through all
essential positions of consciousness to show them their own
limitations; and in their limitations their values.
** One might see this way through the...
** For the varieties of the natural or empirical...
** This self-realizing...
** The dialectical process is on all levels...
** There seems to be, then, in all levels...
** This dialectic is the essential nature of...
This dialectic is the essential nature of consciousness itself.
Every consciousness distinguishes that which it intends and its
own awareness of intending.
** We who know consciousness as this...
** Philosophical knowledge, therefore, distinguishes...
** Consciousness itself is this process of...
** This dialectical movement, in which consciousness...
** The unity and coherence of the process itself...
** The realm of truth is inseparably one with our...
The realm of truth is inseparably one with our tentative
and provisional trials of existence; there is not a moment
of truth which is not also a shape of living consciousness.
