* Relations as a Foundation for Mathematics
** Primitive Concepts
Two primitives:
- *RELATION*
- *POSSIBILITY*

Secondary primitive concepts will be various particular relations.

Possibility is of two kinds:
- Intrinsic
- Extrinsic

Possibility is covered in the section on the Ontological Argument

Relations have three essential characteristics
- They are *SIMPLE*
- They have both *INTRINSIC* and *EXTRINSIC PROPERTIES*
- One of the intrinsic properties is an *ADICITY*

The intrinsic properties of a relation are what determines the
*KIND* of the relation that it is, and the extrinsic properties
determine the *INSTANCE* of that kind.

Extrinsic properties are defined by means of skew-separability:

A is *SKEW-SEPARABLE* from B if A can exist without B,
but B cannot exist without A.

If a relation R is skew-separable from another relation, S,
the R is a *LOWER EXTRINSIC PROPERTY* of S, and S is an
*UPPER EXTRINSIC PROPERTY* of R. And a property of a relation
is an *INTRINSIC PROPERTY* of that relation if the relation
and the property are inseparable.

A primitive relation which exists independently of any
mind is a *REAL RELATION*.

A primitive relation which exists within a mind is an
*IDEAL RELATION*, also called an *ABSTRACT IDEA*.

A relation which is either real or ideal is a *GENUINE RELATION*,
also called an *INTENSIONAL RELATION*. 

A subset of a Cartesian product is an *EXTENSIONAL RELATION*

A grammatical form of words that indicates a relation is
called a *NOMINAL RELATION*; if it does not refer to either
a genuine relation or an extensional relation then it is
called a *PURELY NOMINAL RELATION*.


** Sets
An *INTENSIONAL SET* is a plurality united by a relation.

A *MEMBER* of an intensional set is any one element of the
unified plurality; the relation between a member and its 
set is the relation of *SET-MEMBERSHIP*.

The *EXTENSION* of an intensional set is its plurality.

The *INTENSION* of an intensional set is the commonality of
its plurality: those properties, intrinsic or extrinsic,
possessed by all and only the members of the set; as such
the intension is an extrinsic property of each member.

The *FUNCTION EVERY* is the necessity relation which has
intensions as its arguments and intensional sets as its
values; its inverse is the *FUNCTION ANY*.

The *TERM SET* of a relation R is the intensional set
consisting of every term of R; it is symbolized by the
same letter, italic: /R/.

The *INTRINSIC PROPERTY SET* of a relation R is the 
intensional set of every upper extrinsic property of
R; it is symbolised by the same letter, in parens: (R).

The *EXTRINSIC PROPERTY SET* of a relation R is the
intensional set of every upper extrinsic property
of R. 

A *SET RELATION* is a relation having only the intrinsic
properties of an adicity and simplicity.
** Three Kinds of Mathematical Meaning
** Mathematical Reasoning
A *RELATIONAL MEANING* is the relation that unifies an intensional set.

A *COMPOUNDABLE RELATION* is any kind of relation that has one or more
properties which are also possessed by the relation which unites a set
of instances of that kind. A *COMPOUND RELATION* is an extrinsic 
intensional set of compoundable relations, whose relational meaning
is of a kind similar to, or a superintension of, the kind of its
members.
 
** Foundations
** Some Theorems
