#+TITLE:     Intensional Theory of Mind
#+AUTHOR:    Greg
#+EMAIL:     greg@greg-Satellite-C855D
#+DATE:      2013-08-29 Thu
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:2 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

* Motivation: Leibniz-Russell Theory
Source: http://en.wikipedia.org/wiki/User:Helier_Robinson/Leibniz-Russell_theory_of_perception

Although logically simple this theory is psychologically difficult because of its anti-common-sensical nature; but this difficulty is worth enduring because of the solutions the theory provides to all known philosophical problems of perception.

The theory arises from the contention that all that we perceive around us is not reality (as common sense demands) but images of reality. Because common sense is being impugned it is worth considering some arguments for each side of this question.

People generally agree that perception is a process of information transfer from real objects to images thereof, inside the brain of the perceiver. Common sense has it that the real objects are outside the perceiver's head, public, and material, while the images are inside the perceiver's head, private, and mental. Since what we perceive is external, public, and material, common sense considers all of it to be real.

Against this view are three arguments. The first is that the data that arrives in the perceiver's consciousness takes the form of sensations: tactile sensations (rough, smooth, hard, soft, hot, cold, etc.), colors in various shapes, sounds, tastes, and smells. Since every object that we perceive in the world around us is a structure of sensations, and the whole perceived world is a structure of such objects, the world that we each perceive must be inside our heads, private and mental.

Second is the argument that no perceived object is wholly free of illusion, so no perceived object is real, since no illusion is real. (Can you point to any object that is wholly free of illusion? And if you think you can, can you say how you know it to be so?)

Third is the argument that everyone's perceived world differs qualitatively from everyone else's because of viewpoint and perceptual idiosyncracies; and each of these worlds differs qualititatively from the real world because of illusion; and since qualitative difference entails quantitative difference there must be as many perceived worlds as there are percievers, and none of these perceived worlds are the real world. (The proof that qualitative difference entails quantitative difference is simple: whatever A and B may be, if they differ qualitatively then there is some quality, Q, that A has and B does not have (or vice versa); if A nd B are one then one thing is at once Q and not-Q, which is impossible --- so A and B are two.)

The resolution of these two conflicting positions --- the Leibniz-Russell theory --- comes about with the observation that one's own body is a perceived object, composed of sensations, and thus an image of one's own real body. So the perceiver has two heads: a real head and an image head. The real head is made of animate cells and the image head is made of sensations. Outside the real head is the rest of the real world, the local part of which is imaged into the real brain as structures of sensations, all of which are outside the image head and all of which appear to be material and public. This publicity is publicity by similarity, as the contents of one television program, on different sets, are public by similarity --- as opposed to the publicity by identity that is assumed in common sense.

Although it is not necessary to attend to this theory in daily living, any more than one attends to the speed at which the Earth is going round the Sun, the theory is very important in philosophy. Not only does it solve problems of perception, such as how illusions such as the railroad lines meeting in the distance are outside our heads, public, and material; but it is also valuable in philosophy of science. One of the problems of philosophy of science is the question of why there are two kinds of science, empirical and theoretical; and why empirical science deals with perceptible things and theoretical science with strictly imperceptible things. ('Theoretical' means 'non-empirical'.) Empirical science tries to describe the public features of empirical (image) worlds while theorteical science tries to describe the real world. Since in the process of perception real objects cause images of themselves in empirical worlds; and since to describe causes is to explain their effects, it follows that theoretical science explains what empirical science describes. This theory also is able to explain how theories can predict empirical novelties, as Maxwell's equations predicted radio.

The best treatment of the theory in Russell's works is in Part 3 of Human Knowledge, Allen and Unwin, London, 1948. Russell attributed the theory to Leibniz, where it can be found in his Monadology, included in Loemker, Gottfried Wilhelm Leibniz, Philosophical Papers and Letters, Chicago Univ. Press, 1956. However Leibniz, who feared public opprobium, did not draw attention to the theory, nor to its power.


* Intensional Theory of Mind
Notes on the Intensional Theory of Mind presented by Helier Robinson in his 
work /Relation Philosophy of Mathematics, Science, and Mind/.

The works consists of four chapters
- Mind
- The Oge
- Gods
- Rational Mind

There are three agents in the *noumenal mind*
- Ego (page 148)
- Oge (page 161)
- Psychohelios (page 185)

Three ambiguities (page 185)
- Psy <-> Noumenal World (Ambiguity of Reality)
- Ego <-> Empirical Body (Ambiguity of Self)
- Oge <-> Empirical Society (Ambiguity of Society)

** Mind
An *atomic idea* is a neural switching (0/1) in a noumenal brain.

Two principles:
- *MIND HEKERGY PRINCIPLE*
- *LIKE-ATTRACTS-LIKE-AND-REPELS-UNLIKE* (LALRU)

A *NOUMENAL MIND* is all the atomic ideas in a noumenal brain,
plus all innate ideas, plus all data that are brought in by
the noumenal afferent nerves, plus all that emerges cascadingly
out of these.

Two basic processes within a *NOUMENAL MIND*
- *MAPPING*
- *BONDING*

A *NOUMENAL SENSATION* (or *MID-SENSATION*) is a level-two
structure of atomic ideas, brought into the noumenal mind
by noumenal perception.

A *MID-OBJECT* is a level-three structure in a noumenal mind,
a structure of noumenal sensations.

A *MID-WORLD* is a complete structure of mid-objects. 

The *EGO* is a structure of *EGO-MEMORIES*, mutually
attracted by LAL because of their common feature of
a *MID-MEMORY* of the *MID-BODY*.

An *EMPIRICAL SENSATION* is the LAL reaction in the ego
to a mid-sensation; it is a poor image of a mid-sensation,
mapped by LAL.

An *EMPIRICAL OBJECT* is the LAL reaction in the ego to a
mid-object, hence it is an image of that mid-object.

In short:
- A mid-object is a structure of mid-sensations
- An empirical object is a structure of empirical sensations

An *EMPIRICAL WORLD* is a structure of empirical objects, an
image of a mid-world; and thereby, transitively, of a portion
the noumenal world.

The *AWARENESS* or *CONSCIOUSNESS* of the ego is the
presence of empirical objects within the ego; they are the objects
of this consciousness.

The ego is conscious, over time, of a series of transient empirical worlds.

This consciousness is empirical perception.

Any empirical world, empirically perceived at any one time by an ego,
is entirely within the structure of the ego.

Beyond the empirical blue sky are the outer limits of the ego.

Beyond those outer limits is the inside surface of the ego's noumenal skull.

The LAL forces that produce the consciousness of the ego
depend upon the structure of the ego, and the hekergy of the 
ideas within it, as well as upon the mid-objects that are 
the immediate causes of the consciousness--in accordance
with the LAL formula.

The *ATTITUDE* of the ego is the effect of its permanent
structure on its consciousness.

*SELFISHNESS* is the attitude of the ego that results from
the mind hekergy principle.

*ATTENTION* is the ego's focussing of its consciousness.

Attention focusses on three kinds of content of consciousness:
- Sensations
- Relations 
- Hekergies

*ABSOLUTE VALUES* are noumenal values, actual hekergies

*EMPIRICAL VALUES* or *HUMAN VALUES* are the ego's 
consciousness of images of absolute values.

Consciousness is usually dynamic: attention does not remain
static for long.

*FEELINGS* are the ego's dynamic attention to values,
as opposed to *THOUGHTS*, which are its dynamic attention
to sensations and relations.

A *GOAL* of the ego is any possibility of its own hekergy
increase of which the ego is conscious.

*PLEASURE* is the ego's consciousness of hekergy increase
and *PAIN* is its consciousness of hekergy decrease.

An *EMPIRICAL MEMORY* is the ego's consciousness of a 
mid-memory.

A *CONCRETE QUALITY* is any empirical sensation.

A *CONCRETE IDEA* is an empirical memory of a concrete
quality, or a structure thereof.

A structure of concrete qualities is an empirical object.

Concrete qualities are the smallest elements of empirical
perception, as opposed to atomic ideas, which are the
smallest elements of the noumenal world.

Empirically, a sensation is a level-one structure, an
object is a level-two structure and a world is a level-
three structure.

Empirical Sensation -> Level-One
Empirical Object    -> Level-Two
Empirical World     -> Level-Three

An *ABSRACT IDEA* is any intensional meaning in the 
noumenal mind.

The ego may manipulate ideas at its periphery by appropriate
focussing of its consciousness. Its consciousness of these
processes is either imagination or thought.

*IMAGINATION* is the ego's manipulation of, and consciousness of,
concrete ideas.

*THOUGHT* is the ego's manipulation of, and consciousness
of, abstract ideas.

A *PROPOSITION* is a structure of abstract and/or concrete
ideas.

A *BELIEF*, by the ego, is a proposition that is incorporated
into the structure of the ego, by LAL.

The ego consists of mid-memories and mid-beliefs, and also
of innate ideas. This is quite plausible, in that, once it
has speech, any ego might say existentially "I am what I
have inherited, experienced, and done, and what I believe."

A *PREJUDICE* is a structure consisting of a belief and
supporting evidence for that belief; by LAL the belief
attracts evidence in favour of itself (that is, /like/
itself) and repels evidence against itself (that is,
/unlike/ itself).

*CLASSIFICATION* is the process of collecting similar ideas
into extensional sets, by LAL.

*RECOGNITION* results from the comparison of a present
perception with a memory, such that the comparison yields
similarity; the memory is attracted to the present perception
by LAL and the recognition is consciousness of the similarity.

A *MOTOR-IDEA* is a mid-idea that may be sent down the
efferent nervous system so as to produce a specific movement
of muscles in the noumenal body.

By analogy with computer theory, motor-ideas are instructions
rather than data, yet consist of the same informational
stuff: structures of atomic ideas.

An *ACTION-POINT* is the point in the noumenal mind,
at which a motor-idea is delivered to a set of efferent
nerves.

Efferent or motor nerves, carry nerve impulses AWAY from the central nervous system

Afferent or sensory nerves, carry nerve impulses TOWARDS the central nervous system

*ACTION* by the ego is control of the noumenal body by means
of motor-ideas. The movement of motor-ideas to their action
points by the ego is the *WILLING* of that action by the ego.

A *WORD* is a structure of noumenal and empirical ideas
bonded together, consisting of a memory of the sound of the
word, the motor ideas to produce a similar sound, and a 
noumenal idea that is the meaning of the word; it usually
also has bonded to it a memory of a written word and the
motor ideas to produce a similar written word; and it may
have similar structures bonded to it that are synonyms,
and special symbols or foreign words having the same
meaning.

The *CONCRETE MEANING* of a word is extensional-any,
one member of that class of concrete memories which
is the meaning of the word.

A *PROPER NAME* is a word bonded to a single object.

A *CONCRETE NAME* is a word bonded to a concrete meaning.

A *CONCEPT* is a word bonded to an abstract idea.

*GRAMMAR* consists of rules that relate words and the
meanings of words.

A *SENTENCE* is a set of grammatically related words.

*PURE THOUGHT* is manipulation of abstract ideas--
intensional meanings--without associated language.

*ORDINARY THOUGHT* is manipulation of abstract ideas
with the aid of language--manipulation of concepts.

*CALCULATION* is algorithmic thought: manipulation of words
without their associated abstract ideas, in accordance
with rules derived from ordinary thought.

*DISCRIMINATION* is consciousness of the results of special
mappings, such as the following:

A *PATCH MAPPING* is a mapping of a minimal area of a 
concrete original, just large enough to be within
consciousness.

A *BOUNDARY MAPPING* is a mapping of boundaries--of
contiguous dissimilarities.

A *SCALE MAPPING* is a mapping with uniform enlargement
or diminution.

The *MATERIAL* is everything in the consciousness of the ego
that is external, public, reperceptible, and causally coherent.

The *MENTAL* is everything in the consciousness of the ego
that is not material.

*VANITY* is a false belief that the hekergy of the ego is
greater than its actual value.

*RATIONALISATION* is the manufacture, by the ego, of a false
belief that supports vanity.

** The Oge
Among the irrational features of mind which prevent knowledge
of the best of all intensional mathematical systems are:

- Internal Conflict 
- Social Pressures

Both of these require the concept of oge for their
explanation.

The *OGE* (rhymes with /bogey/) is a second agent in the
noumenal mind which grows out of mid-memories of other
people; as such it represents, and acts on behalf of, society.

*APPROVAL* is evaluation of an action as hekergy increasing;
*DISAPPROVAL* is evaluation of it as hekergy decreasing.

*INTROJECTION* is the incorporation of a proposition into
the oge, thereby making it an oge-belief, as a result of
another person asserting this proposition in the hearing
of the ego.

The *MORAL* is any increase in the hekergy of society,
and hence of the oge.

*GUILT*, *SHAME*, *EMBARASSMENT* and *CONSCIENCE* are
feelings produced in the ego by the oge.

*CONFLICT* occurs when there are two agents having
mutually exclusive goals in a common situation.

An *OGE-INHIBITIION* is the prevention, by the oge,
of an action willed by the ego. An *EGO-INHIBITION*
is the prevention, by the ego, of an action willed
by the oge. A *TABOO* is a very strong oge-inhibition.

An *OGE-COMPULSION* is the forcing, by the oge, of
an action against the will of the ego; an 
*EGO-COMPULSION* is the forcing, by the ego, of
an action against the will of the oge.

An *OGE-PERSON* is a set of mid-memories of a
particular noumenal person, in the oge.

*GOOD* is hekergy increase.

*EVIL* is hekergy decrease.

*LOVE* is a willingness to raise the hekergy of
another person, unconditionally.

*HATE* is a willingness to lower the hekergy of
another person, unconditionally.

The *TOP (HIGH) EGO* is the good pole of the ego.

The *BOTTOM (LOW) EGO* the evil pole of the ego.

*MATURATION* of agents is hekergy increase.

*IDENTIFICATION* occurs when an oge-person, or a
group of them, becomes joined to the ego.

*INCLINATION-DUTY CONFLICT* is conflict between the
ego and the public portion of the oge.

*NEUROTIC CONFLICT* is conflict between the ego and
private portions of the oge.

*NOUMENAL POSSESSION* (*OWNERSHIP*) is an emergent
relation between a noumenal person or group of
noumenal people (the owner/s), and a noumenal object,
characterised by control of the object by the owner,
and lack of such control by non-owners.

*NOUMENAL WEALTH* is the emergent relation between
the hekergy of a noumenal object and a noumenal need
of the possessor of the wealth.

*MATERIAL WEALTH* is the emergent relation between the
hekergy of a material--that is,empirical--object and
an empirical need of the possessor of the wealth.

** Gods
The theory of mind provides six meanings for the word God,
all of which conform in one or more ways to the traditional
uses of the word.

The *OGE-GOD* is the oge.

The *HOLY SPIRIT* is the mind hekergy principle.

The *DEIFIED TEACHER* is the oge-person of a revered religious teacher.

The *PANACEA GOD* is a prejudice.

The *PHILOSOPHER'S GOD* is the noumenal world.

The *PSYCHOHELIOS* is the god of the mystics, the god of truth.

** Rational Mind

*CREATIVITY* is the talent for novel, original, hekergy increase.

A *GENIUS* is anyone with exceptional creativity.

*INTELLIGENCE* is the capacity to rearrange ideas rationally.

The *PSYCHOHELIOS* is that part of the ego that is wholly
rationally ordered.

The *SUPRARATIONAL* is the state of a noumenal mind that 
has maximum possible emergent hekergy.

The *ETHICAL* is anything that moves the individual towards
the suprarational.

*** Illusions of Irrationality
Some of the strangeness of the suprarational comes from
the illusions of irrationality, of which there are at
least ten.

- Illusion of Individuality 
- Illusion of Individual Death
- Everything concrete is illusory
- Illusion of one's own empirical body
- Illusion of subjective coordinate space
- Illusion of chance
- Illusion of free will
- Illusion of good/evil
- Illusion of the sensation of the passage of time
- No intrinsic sets or contingent sets in the world.

In conclusion, because of the nature of intensional
mathematics, of the psychohelios, and of the noumenal
world, we can say that mathematics, theoretical science,
metaphysics, ethics, and theology are ultimately all
the same quest for suprarational truth. And all of 
them, if properly done, are like the present work in
having cascading emergence of definitions and
explanations-- in having intensional meaning. 

* References
