#+TITLE:     Notes on the Helier Robinson's Philosophy of Mathematics
#+AUTHOR:    Greg Dean
#+EMAIL:     greg@greg-Satellite-C855D
#+DATE:      2013-08-31 Sat
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

* Intensional Philosophy of Mathematics
** Preface

A *PURELY INTENSIONAL MATHEMATICS* has two merits:

- Axiom Generosity
- Freedom from Paradox

Main Problems in the Philosophy of Mathematics

1. What is it that determines mathematical inferences,
as if there were a separate Platonic reality which
mathematics describes but cannot alter?

2. Why are axiom sets in mathematics so rich in consequences,
so generous with theorems?

3. What is the explanation of both the power and the beauty
of mathematics, each of which puts mathematics in an entirely
different category from all other languages?

4. What is the difference between mathematical discovery and
mathematical invention? And, whichever is involved, what is
the origin of mathematical novelty?

5. Why is mathematics so effective in describing the world?

6. Given our distinction between intensional, extensional,
and nominal mathematics, what is the extent of intensional
mathematics.

Here are some answers to the questions above:

/Mathematical Inferences/ are based on relations of necessity,
or extrinsic properties that include necessity.

/Axiom Generosity/ is due to cascading emergence of relations.

Mathematics is /Effective In Describing the World/ because 
reality is relational and mathematics is our language of 
relations. 

To explain the power, beauty and novelties of mathematics
we need a concept called /hekergy/.

** Hekergy
The concept of hekergy comes from a generalization of
the concept of negative (or negated) entropy.

If a relation R emerges with the number /e/ of arrangements
of its term set /R/, and there are /t/ possible arrangements
of its terms altogether, so that the probability of the
whole defined by R, given /R/, is the ratio /e/t/, then
the *IMPROBABILITY OF THE WHOLE* is the ratio /t/e/.

A measure of the *ENTROPY*, S-R, of a relation R is
the natural logarithm of the probability of R, ln(e/t);
and a measure of the *HEKERGY*, H-R, of R, is the
natural logarithm of the improbability of R, ln(t/e).

The *EMERGENT HEKERGY* of a whole is the hekergy of
its top relation.

The *SUMMATION HEKERGY* of a whole is the sum of the
total hekergies of all of the terms and subordinate
terms of its unifying relation.

*THE PRINCIPLE OF CONSERVATION OF HEKERGY* is the
principle that hekergy is neither created nor
destroyed, it is always conserved.

The *EMERGENT LEVEL* of an intrinsic relational
property is the lowest level at which that property
may emerge.

*THE PRINCIPLE OF NOVEL EMERGENCE* is the principle, that,
with some exceptions, every emergent relation has an
emergent level and also that, at that level, it possesses
at least one property not possessed by its terms, or 
by any of its subordinate terms.

A *FIELD* might be defined as a map of how the associated
hekergy changes must occur.

** The Ontological Argument
The *ONTOLOGICAL ARGUMENT* is the argument that intensional
mathematical system that exists is the best of all possible
intensional mathematical systems, and that it is exists 
necessarily because it is the best.

- *BEST* is defined by means of /Axiom Generosity/.
- *EXISTENCE* is defined by means of /Logical Consistency/.

Intensionally, a *MATHEMATICAL ENTITY* is any intensional meaning.

*INTENSIONAL MATHEMATICAL EXISTENCE* is possibility: if a
mathematical entity is possible in an intensional mathematical
system then it exists in that system, and if it is not
possible then it does not exist in that system. If the
possibility is singular then the existence is *NECESSARY EXISTENCE*.

A *POSSIBLE WORLD* is a complete logically possible
mathematical system: everything in it is intrinsically 
possible, and is extrinsically possible with everything
else in it. It is an intensional intrinsically possible
world, but it is called a possible world for short.

A possible world has to be *COMPLETE*: if anything more could
be added to it, that addition would be possible in that
world and so already exists in it.

The level of the top relation of a possible world is the
*TOP LEVEL* of that world.

The prime level of relations in a possible world is called
its *PRIME AXIOM STRUCTURE* or *PRIME STRUCTURE* for
short. Relations immediately emergent out of the prime
structure are at /level two/, those next immediately
emergent are at /level three/, and so on.

The totality of relations that emerge cascadingly from a
prime structure is called the *CASCADE* of that prime
structure.

A possible world, unlike other intensional axiomatic
systems, has *CIRCULAR SELF-NECESSITATION*: the existence
of the top relation extrinsically necessitates the
prime structure of that world (top-down necessitation
(or causation), or distributive existence); and the
prime structure extrinsically necessitates the 
emergent cascade (bottom-up necessitation (or causation),
or compositional existence). 

There are two possible definitions of the *QUALITY* of
a possible world, which are here assumed to be
equivalent; that is equivalent in the sense that 
each is a maximum in the best of all possible worlds.
The first is the numerical value of the top level
of a possible world. The second is the magnitude of
the total cascading hekergy of a possible world,
divided by the number of relations in its axiom
structure. If a world has the highest possible
quality it is called the *BEST OF ALL POSSIBLE WORLDS*,
and is symbolized by *G*.

Because *G* has a higher hekergy than any other possible
world, it has maximum possible mathematical beauty.

The property that this one intrinsically possible world
has, which thereby renders all others extrinsically
impossible, is called *MATHEMATICAL ACTUAL EXISTENCE*,
as opposed to the mathematical possible existence
which is intrinsic or extrinsic possibility and
possessed by every possible world. We call this one
world the *ACTUAL WORLD*.
