* Intensional Philosophy of Science
** Problems in the Philosophy of Science
** Observation
The *EMPIRICAL* is anything known through the senses, anything observable.

The *THEORETICAL* is the non-empirical, anything not known through the
senses, but is known by means of the mind, and for which there are good
grounds for belief.

*EMPIRICAL REALITY* is all that we perceive around us that is
potentially universally public.

*NOUMENAL REALITY* is all that exists independently of being observed.
It is what theorists try to describe with theories, or what is usually
described as the underlying causes of empirical reality.

*COMMON SENSE REALISM* is the belief that the empirically real 
is noumenally real.

*EMPIRICAL PERCEPTION* is perception as we know it in everyday experience.

*THEORETICAL PERCEPTION* is the scientific explanation of empirical
perception; it describes *NOUMENAL PERCEPTION*.

The *GENERAL PROBLEM OF PERCEPTION* is the problem of deciding
whether all that we empirically perceive around us is
reality or images of reality.

The *IDENTITY ERROR* is the contravention of the logical principle
that *QUALITATIVE DIFFERENCE ENTAILS QUANTITATIVE DIFFERENCE*.

The *EMPIRICAL WORLD* of any one person, at any one time, is
all that they empirically perceive at that time.

The *NOUMENAL WORLD* is all that is noumenally real.
** The Leibniz-Russell Theory
The observations of two people are *PUBLIC BY IDENTITY* if
they both observe one and the same, or identical, thing.

The observations of two people are *PUBLIC BY SIMILARITY* if
they both observe numerically distinct things which have a
fair degree of similarity between them.

The observations of two people are *PRIVATE BY PLURALITY* if
they are not public by identity--if the observations are two,
not one.

The observations of two people are *PRIVATE BY DISSIMILARITY* if
they have some degree of dissimilarity.
** Applications of the Leibniz-Russell Theory
*NOUMENAL CAUSATION* is relations of necessity in the noumenal
world. The antecedents of such relations are *NOUMENAL CAUSES*
and the consequences are *NOUMENAL EFFECTS*.

*EMPIRICAL CAUSATION* is exclusively extensional functions
among empirical data, characterised by universality.
The arguments of these are *EMPIRICAL CAUSES* and their
values are *EMPIRICAL EFFECTS*.

*INTENSIONAL SCIENCE* is science whose theory is applied 
intensional mathematics.

*EXCLUSIVELY NOMINAL SCIENCE* is all false claims to
empirical data, scientific laws, or theories.

*EXCLUSIVELY EXTENSIONAL SCIENCE* is the science of
empirical extensional sets; it is neither intensional
nor exclusively nominal.

