* Cosmic
Notes on Helier Robinson's /Cosmic Coincidences/.
http://arxiv-web3.library.cornell.edu/abs/1111.4562
** Abstract
   Arising out of an attempt at a new foundations of mathematics, in which relations are more primitive than sets, and out of the theoretical physicists' concept of underlying causes of empirical phenomena, the idea of a purely mathematical possible world (of underlying causes) is developed. It is shown that at least one, and at most one, possible world is actual, and that the one that is actual is the best (as in the philosophy of Leibniz), and therefore requires the cosmic coincidences to exist. This best is actual necessarily because of having a higher level top relation than any other possible world, and because of this top relation possessing the property of intrinsic necessary existence. 
** The Problem of Cosmic Coincidences
The /Problem of Cosmic Coincidences/ refers to the improbability
of certain parameters in theoretical physics having the values
that they do. Following Lee Smolin (Smolin, 1997) Robinson lists
four solutions to this problem:

- Anthropic explanation
- Fine-tuning explanation
- One consistent mathematical system
- Universes emerge from black holes

For Robinson, none of these options are satisfactory, so he posits
a fifth explanation, which derives from the work of GW Leibniz.
Leibniz claims that the "actual world exists necessarily because
it is the best of all possibles." The world that Leibniz refers
to is not the world of empirical phenomena that we experience, but
rather the world of underlying causes of these empirical phenomena.

So for Robinson, there are two worlds, the /EMPIRICAL WORLD/ and 
the /UNDERLYING WORLD/, and it is crucial for the argument that 
we are clear about which of these worlds that we are talking about.

The core of the argument rests on the concept of /NECESSARY EXISTENCE/
or /ACTUALITY/. According to Robinson: "If this concept is neither 
self-contradictory nor implies a contradiction, then whatever has
this necessary existence must exist in at least one among all 
possible worlds, making that one possible world actual."

** Relational Philosophy of Mathematics
Robinson's argument rests on a philosophy of mathematics
based on relations rather than sets. According to Robinson,
in set theory, the defintion of relations "involves a 
vicious circle": the definition of relations as subsets
of Cartesian products presupposes the relation of set
membership and the relations of logical argument forms.

Since relations (arguably) are more important than sets
in mathematics, and sets can be defined easily in terms
of relations, relations should be made fundamental in
mathematics.

Once relations are made fundamental, we can distinguish
between three kinds of defined sets:

- Intensional sets
- Extensional sets
- Nominal sets

The /INTENSION/ of a set (if it has one) is all those properties
that all and only its members possess.

The /EXTENSION/ of a set is the totality of its members.

A /NOMINAL SET/ is a set that has a name or a description but
otherwise does not exist.

From this we obtain three kinds of mathematical meaning: intensional,
extensional and nominal meaning. Only nominal meaning can lead to
contradictions or paradoxes, while only intensional meaning can
have axiom generosity.

Intensional meaning is essentially relational: relations and 
their properties constitute relational meanings. Thus, if 
mathematics is to be rich and consistent, it must be confined
to intensional meaning. This leads to the conclusion that
many common concepts have no intensional meaning. For instance,
neither the concepts /INFINITY/ or /CHANCE/ have intensional
meaning.

** Properties of Relations
In the paper, Robinson identifies a variety of properties of relations in 
general.

A relation has /TERMS/ which are what it relates.

All and only relations have terms. The number of terms a relation 
has is called its /ADICITY/.

We can see (hear,touch,smell,taste,etc.) relations, but we cannot 
say what they look like. For instance, we can see that a hat is
on his head, but what does "on" look like?

Relations cannot exist if their terms do not exist, and if their
terms do exist the terms must be appropriately arranged for the
relations to exist. When arrangements of terms change so as to
have a relation come into existence, we say that the relation
/EMERGES/ out of those terms and that arrangement. Likewise,
if a change of arrangement causes the relation to go out of 
existence, the relation is said to /SUBMERGE/.

Relations may be terms of other relations.

Relations have /INTRINSIC PROPERTIES/, by which they can be
distinguished. They also have two kinds of /EXTRINSIC PROPERTIES/.

There are two kinds of extrinsic properties:
- The terms of the relation
- The other relations of which they are terms (Upper Extrinsic Properties)

The instrinsic properties of a relation determine the /KIND/
of the relation they are, and their terms determine the
/INSTANCE/ of that kind.

Relations form what might be called /NATURAL SETS/: the sets of
their properties, the sets of their terms, and the sets of their
upper extrinsic properties.

Relations have a value, called their /HEKERGY/. If the number
of arrangements of the terms of a relation with which the 
relation emerges is /e/ and the total possible number of
arrangements of of the terms is /t/ then the hekergy of that
relation is /ln(t/e)/. Hekergy is a generalization to relations
of negative (or negated) entropy.

A /STRUCTURE/ is an arrangement of relations relating relations
which relate relations, to various levels. The lowest level of
these relations is called the /PRIME LEVEL/ of the structure.
Relations at the prime level are called /SEPARATORS/; they 
are characterized by being both terms and relations of these
terms. In general (with two exceptions) each level consists
of structures of lower level structures and various combinations
of separators between them. The exceptions are the prime
level and the top level.

A structure which has many levels of emergence is said to
have /CASCADING EMERGENCE/ out of its prime level. Because
a structure consists of two or more substructures, the
number of structures in a level is smaller than the number
of structures in the next level below. Conversely, as you
go to higher levels the variety of structures increases.

For instance, there are more atoms than molecules, but there
are more varieties of molecular structure than there are
varieties of atomic structure.

At various levels of a structure a relation may emerge that
has a property that does not emerge at any lower level. This
property is called an /EMERGENT PROPERTY/ and the lowest
level at which it emerges in the /EMERGENT LEVEL/.

Examples of emergent relations having novel properties:

- Working order of a simple machine (emergent out of a correct arrangement of its parts)
- The specific function of a particular kind of knot (emergent out of an arrangement of loops and threadings of a cord)
- A melody (emergent out of an arrangement of notes)
- Life (emergent out of arrangements of molecules)
- Mind (emergent out of brain)

** Possible and Actual 
An intensional structure which is complete is called a 
/POSSIBLE INTENSIONAL WORLD/ (or /POSSIBLE WORLD/ for
short) Because a possible world cannot be infinite,
it must have a finite prime level; and because the
number of structures diminishes with the height of
level, it must have a highest level, called its /TOP LEVEL/.

The variety of possible worlds is huge. All these
possible worlds are exclusively intensional: they
consist only of relations and their properties.

The /VALUE/ of a possible world is the sum of the hekergies
of all the emergent relations in that complete structure,
divided by the number of separators in its prime level.

The /BEST OF ALL POSSIBLE WORLDS/ is the one that has
the greatest value; this world is called *G*. It has a 
higher top level than any other possible world. Its
top relation is called *T*.

There are two kinds of mathematical existence:
- Possible existence (logical consistency; both intrinsic and extrinsic)
- Actual existence (see below)

Necessary mathematical existence is existence which is 
necessitated. There are three kinds of extrinsic necessary
existence aned one kind of intrinsic necessary existence.

Extrinsic Necessary Existence I
- /CAUSAL NECESSARY EXISTENCE/
- /LOGICAL NECESSARY EXISTENCE/

Extrinsic Necessary Existence II
- /TOP-DOWN NECESSARY EXISTENCE/

Extrinsic Necessary Existence III
- /BOTTOM-UP NECESSARY EXISTENCE/

There is the possibility of a relation having 
/INTRINSIC NECESSARY EXISTENCE/ (INE). Such a 
relation would exist necessarily by its own
intrinsic property. This existence is actual
existence, the source of all actuality. Note that
because the concept of INE is not self-contradictory
it must, like all intrinsically consistent concepts,
exist in at least one of all possible worlds.

A possible world has /CIRCULAR SELF-NECESSITATION/
in that the existence of its prime level bottom-up
necessitates the existence of all of its cascadingly
emergent relations, including its top relation; and
this top-relation top-down-necessitates the existence
of all lower level relations, including the prime level.

This circular self-necessitation is possible circular
self-necessitation; every possible world possesses it.
If a possible world has a relation that has INE then
the circular self-necessitation is necessary, or actual,
circular self-necessitation. Such a world is thereby
an actual world.


** Summary of Argument
*** Overview of what has been said so far 
- At most one possible world can be actual
- At least one possible world must be actual
- At most one possible world containing a relation possessing INE can exist
- At least one relation possessing INE must exist

The only way in which all these four conditions can occur together
is if this relation possessing INE emerges as the top relation of a
possible world having a higher top level than any other possible
world, which makes the relation possessing INE unique among all
possible worlds. The possible world possessing this unique relation
must be the best of all possibles *G*. This unique relation must
be *T*, possessing the emergent property of INE. Thus:


** Bibliographic Information
