Notes on Hegel's Lectures

* Philosophy of Religion (1827)
source: /Hegel's Lectures on Philosophy of Religion/ (One-Volume
Edition). 1988. Edited by Peter C. Hodgson. University of California Press.
** Editorial Introduction
The "Editorial Introduction" by Hodgson associated with these lectures
is very helpful in gaining understanding about the lectures and their
context.

*** Hegel's Four Series of Lectures on the Philosophy of Religion (1-6)
*** Sources and Editions of the Philosophy-of-Religion Lectures (7-11)
*** Structure, Context, and Distinctive Themes of the Lectures (11-26)
Hegel's God is not a supersensible entity, a "supreme being", but rather
the /ultimate/ condition of possibility for the /totality/ of experience
and for religious experience in particular, the experience of the
"religious relationship" of finite and infinite. (12)

In this sense, the philosophical first principle and the theological
first principle are one and the same: God = absolute idea. (12)

God is actual, "absolute actuality", "actual being in and for itself"--
but only in and through worldly reality, not as a separated, supersensible
entity. (12)

Apart from the world, God's actuality remains abstract, unrealized; in
and through the world, of which God is the ideal condition of possibility,
God becomes concrete, living, true actuality--or absolute /spirit/. (12)

The logical deep structure is grounded in the dialectic of the syllogism,
which is the basic movement of thought itself. (12)

Three moments (figures) of any syllogism (according to Hegel) are:
- Universality
- Particularity
- Individuality/Singularity

Example Syllogism.

- All human beings are mortal
- Socrates is human
- Therefore, Socrates is mortal.

Universal Substance: Human Beings (U)

Particular Quality: Mortal (P)

Individual Subject: Socrates (I)
*** Analysis of the Text of the 1827 Lectures (26-71)

** Table of Contents
**** Introduction (73-110)
**** Part I. The Concept of Religion (111-198)
***** A. The Concept of God
***** B. The Knowledge of God
***** C. The Cultus
**** Part II. Determinate Religion (199-388)
***** A. Immediate Religion, or Nature Religion
***** B. The Elevation of the Spiritual above the Natural
***** C. The Religion of Expediency
**** Part III. The Consummate Religion (389-489)
***** Introduction
***** A. The First Element: The Idea of God In and For Itself
***** B. The Second Element: Representation, Appearance
***** C. The Third Element: Community, Spirit
