Old Testament
```{r}
ot <- c(61,50,33,44,43,28,29,5,39,34,37,35,34,39,13,19,9,41,101,29,10,8,73,72,8,59,19,11,6,9,3,4,7,3,4,4,2,12,3)
length(ot)
sum(ot)
sort(ot)
rev(sort(ot))
plot(ot)
plot(rev(sort(ot)))
ot/sum(ot)
```
The Book of Numbers
```{r}
Numbers0112 <- c(54,34,51,49,31,27,89,26,23,36,35,16)
Numbers1324 <- c(33,45,41,50,13,32,22,29,35,41,30,25)
Numbers2536 <- c(17,65,23,31,40,16,54,42,56,29,34,13)

Numbers <- c(Numbers0112,Numbers1324,Numbers2536)

sum(Numbers)
mean(Numbers)
var(Numbers)
sd(Numbers)
summary(Numbers)
plot(Numbers)
plot(sort(Numbers))
```
New Testament
```{r}
nt <- c(45,30,47,34,44,19,18,12,7,7,6,5,4,3,5,4,2,2,15,5,5,4,6,1,1,2,20)
sum(nt)
length(nt)
sort(nt)
rev(sort(nt))
plot(sort(nt))
mean(nt)
rev(sort(nt/sum(nt)))
hist(rev(sort(nt/sum(nt))))
```
Bible
```{r}
bible<-c(ot,nt)
length(bible)
sum(bible)
mean(bible)
plot(bible)
plot(sort(bible))
mean(ot)
mean(nt)
mean(bible)
```
Census #1
```{r}
reu<-46500
sim<-59300
gad<-45650
jud<-74600
iss<-54400
zeb<-57400
eph<-40500
man<-32200
ben<-35400
dan<-62700
ash<-41500
nap<-53400
tribes<-c(reu,sim,gad,jud,iss,zeb,eph,man,ben,dan,ash,nap)
sum(tribes)
tribes/sum(tribes)
plot(tribes)
plot(sort(tribes))
sort(tribes/sum(tribes))

Judah<-c(jud,iss,zeb)
J<-sum(Judah)

Reuben<-c(reu,sim,gad)
R<-sum(Reuben)

Ephraim<-c(eph,man,ben)
E<-sum(Ephraim)

Dan<-c(dan,ash,nap)
D<-sum(Dan)

divs<-c(J,R,E,D)
sum(divs)
divs/sum(divs)

barplot(divs)
barplot(tribes)
```
Census #2
```{r}
reu2<-43730
sim2<-22200
gad2<-40500
jud2<-76500
iss2<-64300
zeb2<-60500
eph2<-32500
man2<-52700
ben2<-45600
dan2<-64400
ash2<-53400
nap2<-45400
tribes2<-c(reu2,sim2,gad2,jud2,iss2,zeb2,eph2,man2,ben2,dan2,ash2,nap2)
sum(tribes2)
tribes2/sum(tribes2)
plot(tribes2)
plot(sort(tribes2))
sort(tribes2/sum(tribes2))

Judah2<-c(jud2,iss2,zeb2)
J2<-sum(Judah2)

Reuben2<-c(reu2,sim2,gad2)
R2<-sum(Reuben2)

Ephraim2<-c(eph2,man2,ben2)
E2<-sum(Ephraim2)

Dan2<-c(dan2,ash2,nap2)
D2<-sum(Dan2)

divs2<-c(J2,R2,E2,D2)
sum(divs2)
divs2/sum(divs2)

barplot(divs2)
barplot(tribes2)

sum(divs)/sum(divs2)
divs-divs2
tribes2-tribes
plot(tribes2-tribes)
barplot(tribes2-tribes)
```
New Testament Divisions
-----------------------

```{r}
par(mfrow=c(1,1))

Lk<-47
Mt<-45
Ac<-44
Jn<-34
Mk<-30

Rv<-21
Ro<-19
C1<-18
He<-15
C2<-12

Ga<-7
Ep<-7
J1<-6
Ph<-6
Co<-5
T1<-5
Jm<-5
P1<-5

H1<-4
T2<-4
P2<-4
H2<-3
Tt<-2
Pm<-2
Ju<-2
J2<-1
J3<-1

Hvy<-c(Lk,Mt,Ac,Jn,Mk)
Mid<-c(Rv,Ro,C1,He,C2)
Lit<-c(Ga,Ep,J1,Ph,Co,T1,Jm,P1)
Fly<-c(H1,T2,P2,H2,Tt,Pm,Ju,J2,J3)
All<-c(Hvy,Mid,Lit,Fly)

barplot(All)
sum(All)
All/sum(All)

sum(Hvy)/sum(All)
sum(Mid)/sum(All)
sum(Lit)/sum(All)
sum(Fly)/sum(All)

sH<-sum(Hvy)
sM<-sum(Mid)
sL<-sum(Lit)
sF<-sum(Fly)

sA<-c(sH,sM,sL,sF)
barplot(sA)
sA
```

