* 2008-White.org
Notes on HC White's /Identity and Control/.

** Summary
The theory expounded in IC is divided into
six sections on social structure (1-6) and 
one chapter on gaining control within these
constraints. The final chapter provides an
overview of the previous 7 and shows how
all the parts fit together.

The book does not read well in exclusively
in a linear order, but must be re-read many
times and in a variety of sequences. Also,
the index is extremely valuable. White has
tremendous erudition and deep understanding
about which works are of high quality, and
which are not. 

** Prologue
** 0. Overview and Contexts. "Putting parts together".
In IC, this chapter comes last, but in my analysis
it comes first. If one has read IC before, but is
returning to it after some time, it is best to start
here. 

In section 8.1.1, IC raises three questions:

- Where is the self?
- Where is consciousness?
- Who is doing all this thinking?


** 1. Identities Seek Control
** 2. Networks and Stories
** 3. Three Disicplines
** 4. Styles
** 5. Institutions and Rhetorics
** 6. Regimes of Control
** 7. Getting Action
