* Ic.org
Notes on H.C. White's /Identity and Control/.

** Identities Seek Control
** Networks and Stories
** Three Disciplines
** Styles
351- Moody and White portray cohesion as what I call a /style/.
** Institutions and Rhetorics
** Regimes of Control
** Getting Action
** Overview and Contexts
351- Moody and White portray cohesion as what I call a /style/.

So the key to understanding /style/ is to understand what Moody and 
White call "cohesion". Turning to that paper, here is the definition
that we have:

*Structural Cohesion*: the minimum number of actors who, if removed from
a group, would disconnect the group.

Structual cohesion simultaneously defines a *group* property
characterizing the collectivity, a *positional* property
that situates subgroups relative to each other in a population,
and *individual* membership properties.

Although the authors do not claim to capture the full range 
of either "solidarity" or "embeddedness", structural cohesion
provides an exact analytic operationalization of a dimension
of each.

Now back to White. On 112-113 he provides his view on
what a style is. Here are some clues.

A *sensibility* is how *style* presents itself in experience.

*Style* can be of any scope and level: it is a scale-invariant concept.


** Glossary
** Bibliography
