* Keys to Hegel
** Motivation
/Keys to Hegel/ is a collection of insights that will
help one understand his thought. 

** Trejo-1993
The /PhG/ is a study of appearances, images and illusions
throughout the history of human consciousness.

Consciousness goes through many stages. Trejo lists the 
following stages of consciousness.

*** The Individual
- Sensory Consciousness [Simple, Infantile]
- Perceptual Consciousness [Common Sense (Aristotle)]
- Understanding Consciousness [Transcendental Apperception (Kant)]

*** The Society
- Self Consciousness [Consciousness of a person developed over time]
- Desiring Self Consciousness [Kinship rivalry]
- Mastery Self Consciousness [Mindframe of the Ruler]
- Servant Self Consciousness [Developed in service to the Master]
- Stoic Self Consciousness [Ideal of honest work and virtue]
- Skeptic Self Consciousness [Cynical resignation to the hard life of a Servant]
- Unhappy Self Consciousness [Ascetic behavior. Leads to the attainment of the truth of Free Will]
- Idealist Consciousness [Makes all ideas into the real. Transcends the Master-Servant-Ascetic frame]
- Rational Consciousness [Supplements the Idealist view with Nature/Substance]
- Empirical Consciousness [Reason only exists in the Object. Empirical observation leads us to Reason]
- Ethical Self Consciousness [Consciousness orients towards family and community]
- Legal Self Consciousness [Realization that others have rights and need to be accomodated]
- Spiritual Consciousness [Understanding that Spirit is Objective. I that is a We.]

*** Society and Culture
- Tragic Consciousness [Recognition of conflicts between duty and guilt]
- Alienation Consciousness [Discipline to required to become a member of cultural elite]
- Lacerated Consciousness [Bohemians, social critics, uses tools of culture against culture]
- Duty Consciousness [Synthesis between (post-Terror) Enlightenment and Pious Conservatives]
- Freedom Consciousness [Willingness to stake life on the politics of freedom for self and community]
- Forgiving Consciousness [Develops as a means to deal with the dark side of humanity]

*** The Church
- Relgious Consciousness [Socialization the Forgiving Consciousness]
- Natural Religious Consciousness [First stirrings of religiosity. Viewed Nature as God(s).]
- Artistic Religious Consciousness [Celebration of sacred people and their sacred activities]
- Revealed Religion Consciousness [Revelation of the Word through literature]

*** The Philosopher
- Spiritual (Geist) Consciousness [Understand Religious consciousness in precise concrete ideas]
- Philosophical Consciousness [The ability to communicate to others the details of consciousness]
- Absolute Consciousness [Synthesis of Religious Love and Philosophical Acumen]

** Wallace on True Infinity
Robert M Wallace has written an article with the intriguing
title "Freedom, Reality, and God: True Infinity as the
Key to Hegel's System". It is interesting to note that on
page 40 in his "Introduction to Hegel's Logic", Justus
Hartnack also writes that one cannot understand Hegel 
until he understands the concept of "True Infinity".
There must be something to this concept then. Let's
look at what Wallace has to say.

"True Infinity" forms a part of one of Hegel's earliest
articles, "Faith and Knowledge" (1802). It remained
with him throughout his career, but to really get 
a grip on the concept, we have to look at the 
/Science of Logic/ (1812-1816,rev.1832), where Hegel
lays it out argues for it in detail.

Hegel's argument is sketched as follows:
- Hegel's reformulation of Kant's concept of freedom.
- Nature of Hegel's "idealism"
- Hegel's theology vs (1) Tradition; (2) Enlightenment

From the above, Wallace argues that even today
Hegel's position, when properly understood, is
as plausible as any now available.

The key topics in Hegel's philosophy (freedom,
reality, idealism, God) are so central to Hegel's
philosophical system as a whole that understanding
these ideas, through the notion of "true infinity"
will also turn about to be the key to understanding
the system.

*** True Infinity and the Reality of Freedom
Quality is characterized by "reality" and "negation".

Reality  -> Immediate
Negation -> Mediated

Something -> Being-for-self -> Concept

Replacement of "ought" by True Infinity

True Infinity is not something that exists
independently, but instead "/is/ only as
a going beyond the finite" (SL 145-146/5:160)

This single "going beyond" (by the finite, of itself)
which constitutes the reality of the finite /and/
of the infinite, is the "unity" of the finite and
the infinite. (SL 144/5:158), through which the
duality of Kant's two worlds or two standpoints
is overcome, /without eliminating/ either world
or either standpoint.

The finite, phenomenal world remains, although
it is identified with this transcendence, by
the finite, of itself. What /is/ eliminated
is the "spuriously infinite" /opposition/,
the supposed compatibility, between the finite
and the infinite, the phenomenal and the 
noumenal.

When the resulting unitary, true infinity is
identified with /freedom/ (SL 138/5:150)--
because going beyond finitude evidently 
involves freedom--the reality of infinite 
freedom is also defended against the objection,
which is raised by naturalism and empiricism
against Kant, that there cannot be two "realities"
that have no intelligible connection with each
other.

In Hegel's picture, there is only one reality,
the true infinity, which includes the finite
because it is the finite's going beyond itself.
It is by going beyond themselves that finitude
and nature become real.

What is actual, true, and perceptible, must
be real; only the true infinity is real; so
empiricism should admit that is only this
infinity and its freedom, and not finite things
as such, that are actual, true, and perceptible.

** True Infinity, Idealism and Hegel's "System"
Recall that for Hegel "something" is "the 
beginning of /subject/", which whill later
reveal itself as what Hegel calls the "Concept".

If there is ONE KEY to Hegel's philosophical
system, it is to be found in this argument to
true infinity.

The main thing that happens in the rest of the 
system is that true infinity is reformulated,
in response to the issue of multiplicity,
into the "Concept" and the "Idea" (which is
the culmination of the /Logic/); and then it
is reformulated even further into "Spirit".

The Concept and the Idea spell out an
understanding of true infinity in terms of
subjectivity and objectivity, and Spirit
spells it out in terms of embodiment in
discrete portions of space and time. It
is not suprising, then, that in the 
/Encyclopedia Logic/ Hegel in fact refers to
true infinity as the "fundamental concept
of philosophy" (EL 95A/8:203)

Points of view
- Third-person (Scientistic) fails to conceive the world as real
- First-person (Infinity) fails to conceive the world as real

The True Infinity is a synthesis of the First and
Third points of view.

*** True Infinity and God
The "spurious infinity" is associated with the Unhappy
Consciousness (/PhG/ 207-230)
