#+TITLE:     Logos Lab
#+AUTHOR:    GW Dean
#+EMAIL:     gwdean@gmail.com
#+DATE:      2013-11-17 Sun
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

A computational toolkit to help one understand philosophical concepts.
* Logical Diagrams (Carlson-2007)
** Borromean Knot
** Game Dynamics
** Steps and Transitions
* Stepping to Infinity (Carlson-2007.(1-102))
** Step 0 Absolute Knowledge
** Step 1 Becoming
** Step 2 Something
** Step 3 Determination of the In-Itself
** Step 4 Limit (Determinateness as Such)
** Step 5 The Ought
** Step 6 Infinity
** Step 7 True Infinity
* The Concept (Lauer-1982.(57-127))
** Overview (57)
** Philosophical Thinking (59)
** The "Necessity" of Truth (76)
** Relation of Thought and Reality (77)
** The Meaning of Concept (80)
This section provides a commentary on sections 
160-164 from the Encyclopedia.

The Concept is "the dynamic reproduction in thought
of the rational structure of reality." (81)

The overall pattern of logical thinking contains three
main parts:
- (1) The Logic of Being
- (2) The Logic of Essence
- (3) The Logic of Concept

The Logic of Being -> the self-development of thought's inevitable
object

The Logic of Essence -> reflection on the object as it is reproduced
in thought

The Logic of Concept -> investigation of the dynamic structure of
thought as expressing the structure of reality  

Subjective Logic and its relation to Reason (82-83)

The process of development (of a Concept) begins with the
subjective concept, that which the thinking of an individual
subject produces, and we must see what this subjective form,
merely as such, involves.

This process of development contains the three "moments":
- Universality
- Particularity
- Singularity

By calling these terms "moments", Hegel indicates that he 
considers them as dynamic elements in a process, each
intelligible only as related to the others in a movement
from one to the other--and back.

UNIVERSALITY designates the character of sameness with
itself that the the concept retains in each of its
instantiations (/Bestimmtheit/).

PARTICULARITY is the generalized instantiation, in which
the self-sameness of the universal remains undisturbed.

SINGULARITY is the ultimate instantiation, wherein are
reflected both the determinacy of the PARTICULAR and the
self-sameness of the UNIVERSAL.

The singular is the same as the "actual thing", but it is
the conceptualized thing, posited in a universal way
as simply this thing identical with itself.

An important thing to remember about the Hegelian concept,
then, is that it is at once Universal, Particular, and 
Singular.

Hegel's /Logic/ can be characterized as a "constantly
repeated defining of God". (85)

The concept is truly first, and "things are what they are
through the activity of the concepts that dwell in them." (85)

Just as divine thought is creative of the conceptual
structure of reality, so human thought is recreative of
a conceptual structure which is antecedent to finite
thinking.

The concept is what is unconditionally concrete, because the
self-contained unity with itself which constitutes the
intrinsic determinateness of singularity is precisely its
relation to itself which constitutes universality.

The relationship between Universality, Particularity and 
Singularity is discussed in depth on page 86. Needs some
digesting before I take thorough notes.

** Judgment (86)
** Syllogism (91)
** From Subjectivity to Objectivity (96)
** The Meaning of "Objectivity" (101)
** The Dynamism of Purpose (104)
Commentary on EpW.(205-207)

In tracing the movement from the subjectivity
of conceptual thinking to the objectivity of
"the concept", the notion of "purpose" is of
utmost importance. (105)

Purpose "realizes itself" in the becoming of
that which is intrinsically ordered to an end.

Purpose is a closed book to "formal" thinking; 
it has to be grasped "speculatively". (106)

** Subject-Object (109)
** Truth as Idea (113)
** Idea as Process (117)
** Idea as Absolute (122)
* God as Spirit (Lauer-1982.(128-161))
** Overview (128)
** Identity of Finite and Infinite Spirit (132)
** Self-Manifestation Essential to Spirit (137)
** Activity Without Passivity (141)
** Only Spirit Knows Spirit (145)
** Relation of Divine Spirit to the World (149)
** Human Self-Consciousness Reveals the Divine (154)
** The Function of Negation (158)
* The Infinite (Lauer-1982.(162-202))
** Overview (162)
** The Infinite Object of Thought (166)
** The Meaning of "Infinite" (170)
** Infinity of Concept (174)
** The Infinity of the Finite (178)
** Phenomenology of Spirit (183)
** Philosophy of Religion (189)
** The Necessary Connection of Thinking and the Reality of God (195)
* Parmenides 
* Computational Monadology.(Steinhart.online)
* 2/27 of the Science of Logic (Houlgate-2006)
* 38 Dialectics in the PhG (Wheat-2012)
* PhG.min
* Resources
- Carlson-2007
- Lauer-1982
- Kontopoulos-1979
- Houlgate-2006
