#+TITLE:     Logos Lab
#+AUTHOR:    GW Dean
#+EMAIL:     gwdean@gmail.com
#+DATE:      2013-11-17 Sun
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:nil skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 

A computational toolkit to help one understand philosophical concepts.
* Logical Diagrams (Carlson-2007)
** Introduction (1-5)
According to Carlson, the "main contribution" of his 2007 book is
that it "reduces every move in Hegel's logic to a discrete diagram".

In all, there are 79 official Logical progressions, organized
in groups of three.

Each official move is diagrammed in a "Figure". Thus, Figure
1(c) (Becoming) is the third sub-step of the first step of 
the Logic. Figure 2(a) (Determinate Being as Such) would be
the first sub-step of the second step.

** Borromean Knot (18-26)
All Middle terms (such as Becoming) are made up of three circles.

- Circle-1: Positive side (Left)
- Circle-2: Negative side (Right)
- Circle-3: Surplus of Positive and Negative (Middle)

These three circles together form a /Borromean Knot/, which 
contains seven distinct areas.

- Areas 1,3,7 are static.
- Areas 2,4,5,6 are dynamic.

Dynamic areas have at least two natures--they are subject to
more than one jurisdiction.

Area-4 is subject to all three jurisdictions.

Area-4 is what Hegel (eventually) calls "being-within-self"   

The Understanding is the intuition that perceives a concept
as an immediate, uncomplicated entity. (19)

Dialectical Reason accuses the Understanding of ignoring
the negative component that dialectic reasoning is able
to comprehend. (21)

Dialectical Reason produces an autistic modulation
between two identical extremes that get us nowhere; drawing
attention to the lack in the Understanding merely replicates
the Understanding's own error.

Speculative Reason "wisely intervenes to stop the 
modulating nonsense". (23)

(...TO BE CONTINUED...)

In terms of our conventions, (2) is the voice of
Dialectical Reason. It is the suppressed voice of (1)
and hence immanent or implicit within (1). Dialectical
Reason merely expresses what was previously hidden.

Likewise, Speculative Reason is the voice of (4),
which is immanent to both (1) and (3). (29)

Every step contains (4), which implies that the prior
steps have never been entirely destroyed. Yet the very
idea of taking a step means that we have negated its
predecessor. Thus (1),(2),and (3) are expelled from
the middle term. Yet the middle term always implies
(1),(2), and (3) in the guise of (4),(5),(6). (29-30)

Sublation--denotes the destruction and preservation
of Logical moments by the more progressive moment
which it generates. (31)

Abstraction turns Pure Being into Pure Nothing. The
modulation itself was Becoming.

Difference must precede Pure Being in origin. Hegel's
beginning is the Understanding's abstraction of 
immediacy from the last step of the Logic.

Reflection notices the difference between Pure Being/
Nothing and Absolute Knowing--an overarching perspective
that comprehends origin and pre-origin at the same time. (32)

* Stepping to Infinity (Carlson-2007.(1-102))
** Step 0 Absolute Knowing (Method)
*** Immediacy (595)
*** Mediation (598)
*** Absolute Knowing (Method) (599)
** Step 1 Becoming 
*** Pure Being (11)
*** Pure Nothing (14)
*** Becoming (15)
From the beginning, Hegel's logic is a play between (a) /stasis/,
(b) /movement/, and, in addition, (c) the unity of stasis and
movement.

Becoming is the first name of that unity.

Becoming represents /movement/. Movement can be perceived
only because it has as background the static, passive
non-movement of Pure Being and Nothing.

Becoming has a dual nature. It arises as the relation
between Being/Nothing and Absolute Knowing. As a relation,
it is /composed/ of simpler parts. It is a complex entity.
In its complexity, Becoming moves. But when we think of
Becoming as such, we freeze it, so that it does not move.
** Step 2 Something
*** Determinate Being (Quality) (48)
*** Quality and Negation (58)
*** Something (63)
** Step 3 Determination of the In-Itself
*** Something/Other (70)
*** Being-for-other/Being-in-itself (73)
*** Determination of the In-itself (78)
** Step 4 Limit (Determinateness as Such)
*** Constitution (79)
*** Constitution v. Determination (82)
*** Limit (Determinateness as Such) (83)
** Step 5 The Ought
*** Finitude (87)
*** Limitation (87)
*** The Ought (88)
** Step 6 Infinity
*** Enriched Finite (92)
*** Another Finite (92)
*** Infinity (93)
** Step 7 True Infinity
*** Spurious Infinity (94)
*** Spurious Infinity and Its Other (94)
*** True Infinity (97)
The Spurious Infinite and its finite beyond modulate
back and forth. The name of this movement is the
True Infinite.

True Infinity resembles, but is more advanced than,
Becoming.

The True Infinite is that which becomes something else
while remaining what it is. (97)

Hegel calls the True Infinite the "fundamental concept
of philosophy".

The contribution of the True Infinite is that it
encompasses both the Finite and its beyond.

In True Infinity, Limit (between the Finites) and 
Limitation (the Other of the Spurious Infinite)
are sublated.

Kant's doctrine of the thing-in-itself depends on
the self-identity of the phenomenal thing. Better
to let the Finite do what it does best--cease-to-be. (99)

The very act of ceasing /is/ True Infinity. (99)

True Infinity, "contradiction as displayed in the
sphere of being", is a higher reality than Determinate
Being. It has acquired a more concrete content and
therefore better deserves the name "reality".

A better word for True Infinity may be /ideality/. (100)

(...TO BE CONTINUED...)

* Absolute Idea (Carlson-2007.(593-603))
* The Concept (Lauer-1982.(57-127))
** Overview (57)
** Philosophical Thinking (59)
** The "Necessity" of Truth (76)
** Relation of Thought and Reality (77)
** The Meaning of Concept (80)
This section provides a commentary on sections 
160-164 from the Encyclopedia.

The Concept is "the dynamic reproduction in thought
of the rational structure of reality." (81)

The overall pattern of logical thinking contains three
main parts:
- (1) The Logic of Being
- (2) The Logic of Essence
- (3) The Logic of Concept

The Logic of Being -> the self-development of thought's inevitable
object

The Logic of Essence -> reflection on the object as it is reproduced
in thought

The Logic of Concept -> investigation of the dynamic structure of
thought as expressing the structure of reality  

Subjective Logic and its relation to Reason (82-83)

The process of development (of a Concept) begins with the
subjective concept, that which the thinking of an individual
subject produces, and we must see what this subjective form,
merely as such, involves.

This process of development contains the three "moments":
- Universality
- Particularity
- Singularity

By calling these terms "moments", Hegel indicates that he 
considers them as dynamic elements in a process, each
intelligible only as related to the others in a movement
from one to the other--and back.

UNIVERSALITY designates the character of sameness with
itself that the the concept retains in each of its
instantiations (/Bestimmtheit/).

PARTICULARITY is the generalized instantiation, in which
the self-sameness of the universal remains undisturbed.

SINGULARITY is the ultimate instantiation, wherein are
reflected both the determinacy of the PARTICULAR and the
self-sameness of the UNIVERSAL.

The singular is the same as the "actual thing", but it is
the conceptualized thing, posited in a universal way
as simply this thing identical with itself.

An important thing to remember about the Hegelian concept,
then, is that it is at once Universal, Particular, and 
Singular.

Hegel's /Logic/ can be characterized as a "constantly
repeated defining of God". (85)

The concept is truly first, and "things are what they are
through the activity of the concepts that dwell in them." (85)

Just as divine thought is creative of the conceptual
structure of reality, so human thought is recreative of
a conceptual structure which is antecedent to finite
thinking.

The concept is what is unconditionally concrete, because the
self-contained unity with itself which constitutes the
intrinsic determinateness of singularity is precisely its
relation to itself which constitutes universality.

The relationship between Universality, Particularity and 
Singularity is discussed in depth on page 86. Needs some
digesting before I take thorough notes.

** Judgment (86)
** Syllogism (91)
** From Subjectivity to Objectivity (96)
** The Meaning of "Objectivity" (101)
** The Dynamism of Purpose (104)
Commentary on EpW.(205-207)

In tracing the movement from the subjectivity
of conceptual thinking to the objectivity of
"the concept", the notion of "purpose" is of
utmost importance. (105)

Purpose "realizes itself" in the becoming of
that which is intrinsically ordered to an end.

Purpose is a closed book to "formal" thinking; 
it has to be grasped "speculatively". (106)

** Subject-Object (109)
** Truth as Idea (113)
** Idea as Process (117)
** Idea as Absolute (122)
* God as Spirit (Lauer-1982.(128-161))
** Overview (128)
** Identity of Finite and Infinite Spirit (132)
** Self-Manifestation Essential to Spirit (137)
** Activity Without Passivity (141)
** Only Spirit Knows Spirit (145)
** Relation of Divine Spirit to the World (149)
** Human Self-Consciousness Reveals the Divine (154)
** The Function of Negation (158)
* The Infinite (Lauer-1982.(162-202))
** Overview (162)
** The Infinite Object of Thought (166)
** The Meaning of "Infinite" (170)
** Infinity of Concept (174)
** The Infinity of the Finite (178)
** Phenomenology of Spirit (183)
** Philosophy of Religion (189)
** The Necessary Connection of Thinking and the Reality of God (195)
* Parmenides (Plato, 1152-1168)
* Computational Monadology.(Steinhart.online)
* 2/27 of the Science of Logic (Houlgate-2006)
* 38 Dialectics in the PhG (Wheat-2012)
* Gospel of John
* PhG.min
* Science of Logic Outline
** Objective Logic
*** Doctrine of Being
**** Quality
**** Quantity
**** Measure
*** Doctrine of Essence
**** Reflection
**** Appearance
**** Actuality
** Subjective Logic
*** Doctrine of Concept
**** Subjectivity
**** Objectivity
**** The Idea
* References
- Carlson-2007
- Lauer-1982
- Kontopoulos-1979
- Houlgate-2006
