* Optimistic Moments in Hegel's Philosophy
** Identity of Finite and Infinite Spirit (Lauer-1982.(132-137))
[F]inite spirit is a manifestation of absolue Spirit knowing 
itself as the totality of both knowing and the known. (132)

The consciousness which finite spirit has of objects as,
so to speak, over-against itself is but an aspect of its self-
consciousness, and this self-consciousness is but a facet
of the overall self-consciousness of absolute Spirit. (133)

Strictly speaking, finite spirit does not /have/ either
consciousness of objects or of itself; it /is/ finite
manifestation of infinite self-consciousness. (133)

Only as identified with absolute Spirit is finite spirit
what it itself really is. (133)

The initiative, so to speak, belongs to infinite Spirit,
whose self-differentiating in the totality of spiritual
activity is the very being of the infinite. (133)

The self-consciousness of infinite Spirit is the very
being of finite spirit. (133)

[Hegel] makes a good case for a progressive development
in the religious conception of God. As man moves from a 
conception of the divine drawn from and rooted in the things 
of nature, through the progressive attempts to portray the 
divine in a variety of art forms, all tending to
anthropomorphize the divine, until the self-conscious
self-revelation of God in the Judeo-Christian tradition
supplants all others--in the West at least--and as this
culminates in the self-revelation of God in the form of
an individual man, whose "spirit" subsequently vitalizes
the religious community, it can be said that the the God
that man believes in becomes more and more "spiritual". (135)

In parallel with this development of God-consciousness
there occurs a growth in man's consciousness of himself as
a spiritual being, a progressive recognition that to be
human is to be spiritual.

Man's "concept" of God and man's "concept" of man develop
hand in hand.

What characterizes spirit, as opposed to things of nature,
is that spirit is not simply "given" as what it is;
it is the activity of making itself, of, we might say,
"progressively realizing itself" as spirit.

The Philosophy of Spirit is divided into following three
parts:

- Subjective Spirit :: Man as natural science sees him.
- Objective Spirit :: Man as he develops rationally.
- Absolute Spirit :: Man as he comes to the realization of all that it is to be spirit.

It is the concept of spirit which makes philosophy intelligible...at the
same time, it is the philosophical comprehension of spirit which makes
religion intelligible.
