* True Infinity
Notes on the concept of TRUE INFINITY from Hegel's
/Science of Logic/.
** Carlson-2005
A FINITE THING, by its own logic, /must/ come to an end.

When it does end, the FINITE THING has become what it OUGHT to be--NOTHING.

Yet for Hegel, NOTHING is SOMETHING.

If the FINITE THING passes away, the memory of it remains.

The FINITE THING obtains an /ideal/ existence when it ceases to be.

In its ideal form, BEING is subject to /recollection/ (inwardization).

TRUE INFINITY is therefore the process of inwardization.

TRUE INFINITY's place in the /SL/ is very portal from /reality/ to /ideality/.

Ideality constitutes the memory of what /was/.

The TRUE INFINITE becomes what it OUGHT to be--but /it also remains what it was/.

The TRUE INFINITE is a /unity/ of its finite self /and/ its beyond.

The TRUE INFINITE constantly removes itself from self-presence to a beyond
/and/ it brings its beyond into its own presence.

This double movement of cancellation and preservation is called /sublation/.

In sublation, the FINITE THING invests itself into the beyond when it
ceases to be, and the beyond invests itself into present thought when
/it/ ceases to be.

With the advent of ABSOLUTE IDEA, the very idea of a 'beyond' becomes
untenable.

In ABSOLUTE IDEA, there is no longer a place to which the TRUE INFINITE
can withdraw. Here the distinction between form and content falls apart.

ABSOLUTE IDEA is absolute form.

ABSOLUTE IDEA must play out the three moments of the Understanding (U),
Dialectical Reason (DR) and Speculative Reason (SR). Indeed, these
moments /literally are/ the U, DR, and SR. The moments identified in
the last chapter /are/ method itself--each one moment implying all
the others as well as itself.
