Notes on /The Future of Religion/ (Stark Bainbridge 1985)
* Overview
** The Nature of Religion
Three fundamental/interrelated processes occurring within
all religious economies
- Secularization
- Revival
- Religious Innovation

The authors argue that sources of religion are shifting
constantly in societies but that the amount of religion
remains relatively constant.
*** Defining Religion
The authors assert that there can be no wholly naturalistic
religion; a religion lacking supernatural assumptions is
no religion at all.

Naturalistic systems cannot replace supernaturalistic
systems in the hearts of most human beings.

Critique of Durkheim's (and others') "overbroad definition"
of religion.

The authors distinguish religions and other ideological
systems using the following conception:

"Religions involve some conception of a supernatural being,
world, or force, and the notion that the supernatural is
active, that events and conditions here on earth are
influenced by the supernatural."

Another way of putting it (from J.G.Frazer): Religion consists
of two elements:
- A belief in powers higher than man
- An attempt to propitiate or please them
** Of Churches, Sects and Cults
* The Religious Economy
* Sect Movements
* Cults
* Recruitment
* Sources of Religious Movements
